project:
  type: book
  resources:
    - "files/"

book:
  title: "Hansalim: the universe in a bowl of rice"
  author: "Jonathan Dolley"
  date: "11/7/2024"
  google-analytics: "G-RQ8H157TLG"
  page-footer:
    left: Copyright 2024 Jonathan Dolley
    center:
      - text: "livingtogether.xyz"
        href: https://livingtogether.xyz
    right:
      - icon: github
        href: https://github.com/JonathanDolley/book.livingtogether.xyz
    border: true
    background: light
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/01_hansalim.qmd
    - chapters/02_history.qmd
    - chapters/03_foundations.qmd
    - chapters/references.qmd
  appendices:
    - appendices/01_farming_blog.qmd
    - appendices/02_illustrated_farming.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
    lightbox: true
    execute:
      echo: false
    comments:
      hypothesis: true
    bibliography: references.bib
    csl: chicago-fullnote-bibliography.csl
